# Generated by Django 3.0.5 on 2020-04-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirapp', '0002_videoview'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='backgroundImg')),
                ('caption', models.CharField(max_length=30)),
            ],
        ),
    ]
