# Generated by Django 3.0.5 on 2020-04-30 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shirapp', '0003_backgroundimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shirapp.Video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
