# Generated by Django 3.0.5 on 2020-04-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirapp', '0004_auto_20200430_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
